name: brighthon_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  dio: ^5.3.2
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  get_storage: ^2.1.1
  get_cli: ^1.8.1
  get: 4.6.6
  package_info: ^2.0.2
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
